package com.own.user.party.address.service;
import com.own.face.trade.TradeException; import com.own.user.party.address.domain.BuyerAddress; import com.own.user.party.address.domain.BuyerAddressGuard; import com.own.user.party.address.dto.AddressCommand; import com.own.user.party.address.repository.BuyerAddressGuardRepository; import com.own.user.party.address.repository.BuyerAddressRepository; import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class BuyerAddressService {
 private final BuyerAddressRepository repository; private final BuyerAddressGuardRepository guards; public BuyerAddressService(BuyerAddressRepository repository,BuyerAddressGuardRepository guards){this.repository=repository;this.guards=guards;}
 @Transactional public BuyerAddress create(Long buyerId, AddressCommand command){validate(command);lockBuyer(buyerId); List<BuyerAddress> all=repository.findByBuyerIdOrderByDefaultAddressDescIdDesc(buyerId); boolean primary=all.isEmpty()||Boolean.TRUE.equals(command.getDefaultAddress()); if(primary) clearDefault(all); return repository.save(new BuyerAddress(buyerId,trim(command.getRecipientName()),trim(command.getMobile()),trim(command.getProvince()),trim(command.getCity()),trim(command.getDistrict()),trim(command.getDetail()),primary));}
 public List<BuyerAddress> list(Long buyerId){return repository.findByBuyerIdOrderByDefaultAddressDescIdDesc(buyerId);}
 public BuyerAddress get(Long buyerId,Long id){BuyerAddress address=repository.findByIdAndBuyerId(id,buyerId);if(address==null)throw TradeException.notFound("address was not found");return address;}
 @Transactional public BuyerAddress update(Long buyerId,Long id,AddressCommand command){validate(command);lockBuyer(buyerId);BuyerAddress address=get(buyerId,id);address.update(trim(command.getRecipientName()),trim(command.getMobile()),trim(command.getProvince()),trim(command.getCity()),trim(command.getDistrict()),trim(command.getDetail()));if(Boolean.TRUE.equals(command.getDefaultAddress())){clearDefault(list(buyerId));address.setDefaultAddress(true);}return repository.save(address);}
 @Transactional public BuyerAddress setDefault(Long buyerId,Long id){lockBuyer(buyerId);BuyerAddress address=get(buyerId,id);clearDefault(list(buyerId));address.setDefaultAddress(true);return repository.save(address);}
 @Transactional public void delete(Long buyerId,Long id){lockBuyer(buyerId);BuyerAddress address=get(buyerId,id);List<BuyerAddress> all=list(buyerId);repository.delete(address);if(Boolean.TRUE.equals(address.getDefaultAddress()))for(BuyerAddress next:all)if(!next.getId().equals(id)){next.setDefaultAddress(true);repository.save(next);break;}}
 private void clearDefault(List<BuyerAddress> values){for(BuyerAddress value:values)if(Boolean.TRUE.equals(value.getDefaultAddress())){value.setDefaultAddress(false);repository.save(value);}}
 private void lockBuyer(Long buyerId){guards.ensure(buyerId);BuyerAddressGuard guard=guards.findByBuyerIdForUpdate(buyerId);if(guard==null)throw new IllegalStateException("buyer address guard was not created");}
 private void validate(AddressCommand c){if(c==null||blank(c.getRecipientName())||blank(c.getProvince())||blank(c.getCity())||blank(c.getDistrict())||blank(c.getDetail())||c.getMobile()==null||!c.getMobile().trim().matches("1\\d{10}"))throw TradeException.unprocessable("recipientName, 11-digit mobile, province, city, district and detail are required");}
 private boolean blank(String v){return v==null||v.trim().isEmpty();} private String trim(String v){return v.trim();}
}
