package com.own.promotion.coupon.domain;
import java.math.BigDecimal; import java.util.Date; import jakarta.persistence.*;
@Entity @Table(name = "mkt_merchant_coupon_template") public class MerchantCouponTemplate {
 @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id; @Column(name = "merchant_id", nullable = false) private Long merchantId; @Column(nullable = false, length = 128) private String name; @Column(name = "total_quantity", nullable = false) private Integer totalQuantity; @Column(name = "minimum_amount", nullable = false) private BigDecimal minimumAmount; @Column(name = "discount_amount", nullable = false) private BigDecimal discountAmount; @Column(name = "claim_starts_at") private Date claimStartsAt; @Column(name = "claim_ends_at") private Date claimEndsAt; @Column(name = "expires_at", nullable = false) private Date expiresAt; @Column(nullable = false, length = 16) private String status; @Column(name = "created_at", nullable = false) private Date createdAt; @Column(name = "updated_at", nullable = false) private Date updatedAt;
 protected MerchantCouponTemplate() { } public MerchantCouponTemplate(Long merchantId, String name, Integer totalQuantity, BigDecimal minimumAmount, BigDecimal discountAmount, Date claimStartsAt, Date claimEndsAt, Date expiresAt) { this.merchantId=merchantId;this.name=name;this.totalQuantity=totalQuantity;this.minimumAmount=minimumAmount;this.discountAmount=discountAmount;this.claimStartsAt=claimStartsAt;this.claimEndsAt=claimEndsAt;this.expiresAt=expiresAt;this.status="ACTIVE";this.createdAt=new Date();this.updatedAt=this.createdAt; } public void setStatus(String value) { status=value;updatedAt=new Date(); }
 public void updateTerms(String name, Integer totalQuantity, BigDecimal minimumAmount, BigDecimal discountAmount,
                         Date claimStartsAt, Date claimEndsAt, Date expiresAt) {
  this.name=name; this.totalQuantity=totalQuantity; this.minimumAmount=minimumAmount; this.discountAmount=discountAmount;
  this.claimStartsAt=claimStartsAt; this.claimEndsAt=claimEndsAt; this.expiresAt=expiresAt; this.updatedAt=new Date();
 }
 public Long getId(){return id;} public Long getMerchantId(){return merchantId;} public String getName(){return name;} public Integer getTotalQuantity(){return totalQuantity;} public BigDecimal getMinimumAmount(){return minimumAmount;} public BigDecimal getDiscountAmount(){return discountAmount;} public Date getClaimStartsAt(){return claimStartsAt;} public Date getClaimEndsAt(){return claimEndsAt;} public Date getExpiresAt(){return expiresAt;} public String getStatus(){return status;} public Date getCreatedAt(){return createdAt;} public Date getUpdatedAt(){return updatedAt;}
}
