package com.own.order.domain;
import java.math.BigDecimal; import org.junit.*;
public class AfterSaleTest {
 @Test public void returnAndRefundFollowsMerchantAndReturnFlow(){AfterSale sale=new AfterSale("AS-1","ORD-1","SUB-1",1L,2L,AfterSaleType.RETURN_AND_REFUND,new BigDecimal("20.00"),"damaged");sale.approve("approved");Assert.assertEquals(AfterSaleStatus.APPROVED,sale.getStatus());sale.submitReturn("DEMO","T-1");sale.receiveReturn();Assert.assertEquals(AfterSaleStatus.REFUND_PENDING,sale.getStatus());sale.refund();Assert.assertEquals(AfterSaleStatus.REFUNDED,sale.getStatus());}
 @Test public void refundOnlyBecomesRefundPendingImmediately(){AfterSale sale=new AfterSale("AS-1","ORD-1","SUB-1",1L,2L,AfterSaleType.REFUND_ONLY,BigDecimal.ONE,"missing");sale.approve(null);Assert.assertEquals(AfterSaleStatus.REFUND_PENDING,sale.getStatus());}
 @Test public void reminderOnlyRecordsItsTimestampWithoutChangingTheState(){AfterSale sale=new AfterSale("AS-1","ORD-1","SUB-1",1L,2L,AfterSaleType.REFUND_ONLY,BigDecimal.ONE,"missing");sale.remind();Assert.assertEquals(AfterSaleStatus.APPLYING,sale.getStatus());Assert.assertNotNull(sale.getLastReminderAt());}
 @Test public void buyerCanOnlyCloseBeforeMerchantAudit(){AfterSale sale=new AfterSale("AS-1","ORD-1","SUB-1",1L,2L,AfterSaleType.REFUND_ONLY,BigDecimal.ONE,"missing");sale.close();Assert.assertEquals(AfterSaleStatus.CLOSED,sale.getStatus());try{sale.close();Assert.fail("closed request cannot be closed twice");}catch(IllegalStateException expected){/* expected */}}
 @Test public void exchangeRequiresBuyerReceiptAfterMerchantShipsReplacement(){AfterSale sale=new AfterSale("AS-1","ORD-1","SUB-1",1L,2L,AfterSaleType.EXCHANGE,BigDecimal.ONE,"wrong size");sale.approve("approved");sale.submitReturn("DEMO","RETURN-1");sale.receiveReturn();sale.exchangeShip("DEMO","REPLACEMENT-1");Assert.assertEquals(AfterSaleStatus.EXCHANGE_SHIPPED,sale.getStatus());sale.confirmExchangeReceipt();Assert.assertEquals(AfterSaleStatus.EXCHANGED,sale.getStatus());}
}
