package com.own.order.domain;
public enum AfterSaleStatus { APPLYING, APPROVED, REJECTED, RETURNING, RECEIVED, EXCHANGE_PENDING_SHIPMENT, EXCHANGE_SHIPPED, EXCHANGED, REFUND_PENDING, REFUNDED, CLOSED }
