package com.own.order.domain;
import java.math.BigDecimal; import java.util.Date; import javax.persistence.*;
@Entity @Table(name="ord_after_sale") public class AfterSale {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="after_sale_no",nullable=false,unique=true,length=64) private String afterSaleNo;
 @Column(name="order_no",nullable=false,length=64) private String orderNo; @Column(name="sub_order_no",nullable=false,length=64) private String subOrderNo;
 @Column(name="buyer_id",nullable=false) private Long buyerId; @Column(name="merchant_id",nullable=false) private Long merchantId;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private AfterSaleType type; @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private AfterSaleStatus status;
 @Column(name="requested_amount",nullable=false,precision=19,scale=2) private BigDecimal requestedAmount; @Column(nullable=false,length=500) private String reason;
 @Column(name="return_company",length=100) private String returnCompany; @Column(name="return_tracking_no",length=100) private String returnTrackingNo; @Column(name="merchant_remark",length=500) private String merchantRemark;
 @Column(name="created_at",nullable=false) private Date createdAt; @Column(name="updated_at",nullable=false) private Date updatedAt; @Column(name="last_reminder_at") private Date lastReminderAt;
 protected AfterSale(){} public AfterSale(String no,String orderNo,String subOrderNo,Long buyerId,Long merchantId,AfterSaleType type,BigDecimal amount,String reason){this.afterSaleNo=no;this.orderNo=orderNo;this.subOrderNo=subOrderNo;this.buyerId=buyerId;this.merchantId=merchantId;this.type=type;this.requestedAmount=amount;this.reason=reason;this.status=AfterSaleStatus.APPLYING;this.createdAt=new Date();this.updatedAt=createdAt;}
 public void approve(String remark){require(AfterSaleStatus.APPLYING);merchantRemark=remark;status=type==AfterSaleType.REFUND_ONLY?AfterSaleStatus.REFUND_PENDING:AfterSaleStatus.APPROVED;touch();} public void reject(String remark){require(AfterSaleStatus.APPLYING);merchantRemark=remark;status=AfterSaleStatus.REJECTED;touch();} public void close(){require(AfterSaleStatus.APPLYING);status=AfterSaleStatus.CLOSED;touch();} public void submitReturn(String company,String tracking){require(AfterSaleStatus.APPROVED);returnCompany=company;returnTrackingNo=tracking;status=AfterSaleStatus.RETURNING;touch();} public void receiveReturn(){require(AfterSaleStatus.RETURNING);status=type==AfterSaleType.EXCHANGE?AfterSaleStatus.EXCHANGE_PENDING_SHIPMENT:AfterSaleStatus.REFUND_PENDING;touch();} public void exchangeShip(String company,String tracking){require(AfterSaleStatus.EXCHANGE_PENDING_SHIPMENT);returnCompany=company;returnTrackingNo=tracking;status=AfterSaleStatus.EXCHANGE_SHIPPED;touch();} public void confirmExchangeReceipt(){require(AfterSaleStatus.EXCHANGE_SHIPPED);status=AfterSaleStatus.EXCHANGED;touch();} public void refund(){require(AfterSaleStatus.REFUND_PENDING);status=AfterSaleStatus.REFUNDED;touch();}
 public void remind(){lastReminderAt=new Date();touch();}
 private void require(AfterSaleStatus expected){if(status!=expected)throw new IllegalStateException("invalid after-sale state transition");} private void touch(){updatedAt=new Date();}
 public Long getId(){return id;} public String getAfterSaleNo(){return afterSaleNo;} public String getOrderNo(){return orderNo;} public String getSubOrderNo(){return subOrderNo;} public Long getBuyerId(){return buyerId;} public Long getMerchantId(){return merchantId;} public AfterSaleType getType(){return type;} public AfterSaleStatus getStatus(){return status;} public BigDecimal getRequestedAmount(){return requestedAmount;} public String getReason(){return reason;} public String getReturnCompany(){return returnCompany;} public String getReturnTrackingNo(){return returnTrackingNo;} public String getMerchantRemark(){return merchantRemark;} public Date getLastReminderAt(){return lastReminderAt;}
}
