package com.own.order.service;

import com.own.face.trade.*;
import com.own.order.domain.*;
import com.own.order.dto.*;
import com.own.order.repository.*;
import java.math.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** P2 request and return state machine backed by the local simulated partial-refund contract. */
@Service public class AfterSaleService {
 private final AfterSaleRepository sales; private final AfterSaleItemRepository saleItems; private final TradeSubOrderRepository subOrders; private final TradeOrderRepository orders; private final OrderItemRepository items; private final OrderEventRepository events; @org.springframework.beans.factory.annotation.Autowired private InventoryClient inventory; @org.springframework.beans.factory.annotation.Autowired private SettlementClient settlement; @org.springframework.beans.factory.annotation.Autowired private AfterSaleEvidenceRepository evidence; @org.springframework.beans.factory.annotation.Autowired private FileClient files;
 public AfterSaleService(AfterSaleRepository sales,AfterSaleItemRepository saleItems,TradeSubOrderRepository subOrders,TradeOrderRepository orders,OrderItemRepository items,OrderEventRepository events){this.sales=sales;this.saleItems=saleItems;this.subOrders=subOrders;this.orders=orders;this.items=items;this.events=events;}
 @Transactional public AfterSale create(TradeActor actor,CreateAfterSaleCommand command){actor.require(ActorType.BUYER);if(command==null||blank(command.getSubOrderNo())||command.getType()==null||blank(command.getReason())||command.getItems()==null||command.getItems().isEmpty())throw TradeException.unprocessable("subOrderNo, type, reason and items are required");TradeSubOrder sub=requireSubForUpdate(command.getSubOrderNo());TradeOrder order=requireOrder(sub.getOrderNo());if(!actor.getId().equals(order.getBuyerId()))throw TradeException.forbidden("buyer does not own this order");if(sub.getStatus()!=SubOrderStatus.SHIPPED&&sub.getStatus()!=SubOrderStatus.RECEIVED)throw TradeException.conflict("after-sale is available only after shipment");if(!sales.findBySubOrderNoAndStatusIn(sub.getSubOrderNo(),Arrays.asList(AfterSaleStatus.APPLYING,AfterSaleStatus.APPROVED,AfterSaleStatus.RETURNING,AfterSaleStatus.RECEIVED,AfterSaleStatus.REFUND_PENDING)).isEmpty())throw TradeException.conflict("sub order already has an active after-sale request");
  List<OrderItem> orderItems=items.findBySubOrderNo(sub.getSubOrderNo());Map<Long,OrderItem> byId=new HashMap<Long,OrderItem>();Map<Long,Integer> appliedQuantities=appliedQuantities(sub.getSubOrderNo());Set<Long> selectedItemIds=new HashSet<Long>();BigDecimal subLines=BigDecimal.ZERO,selected=BigDecimal.ZERO;for(OrderItem item:orderItems){byId.put(item.getId(),item);subLines=subLines.add(item.getLineTotal());}for(AfterSaleItemCommand line:command.getItems()){OrderItem item=byId.get(line==null?null:line.getOrderItemId());int alreadyApplied=appliedQuantities.containsKey(line==null?null:line.getOrderItemId())?appliedQuantities.get(line.getOrderItemId()):0;if(item==null||line.getQuantity()==null||line.getQuantity()<1||line.getQuantity()>item.getQuantity()||alreadyApplied+line.getQuantity()>item.getQuantity()||!selectedItemIds.add(line.getOrderItemId()))throw TradeException.unprocessable("after-sale item quantity is invalid");selected=selected.add(item.getUnitPrice().multiply(BigDecimal.valueOf(line.getQuantity())));}
  List<String> evidenceNames=verifiedEvidence(actor,command.getEvidenceFileNames());BigDecimal discount=subLines.signum()==0?BigDecimal.ZERO:sub.getDiscountAmount().multiply(selected).divide(subLines,2,RoundingMode.HALF_UP);BigDecimal refund=selected.subtract(discount);String no="AS-"+UUID.randomUUID().toString();AfterSale sale=sales.save(new AfterSale(no,order.getOrderNo(),sub.getSubOrderNo(),actor.getId(),sub.getMerchantId(),command.getType(),refund,command.getReason().trim()));for(AfterSaleItemCommand line:command.getItems()){OrderItem item=byId.get(line.getOrderItemId());BigDecimal amount=item.getUnitPrice().multiply(BigDecimal.valueOf(line.getQuantity()));saleItems.save(new AfterSaleItem(no,item,line.getQuantity(),amount));}for(String storedName:evidenceNames)evidence.save(new AfterSaleEvidence(no,storedName));event(sale,"AFTER_SALE_CREATED",actor,command.getReason().trim());return sale; }
 @Transactional public AfterSale audit(TradeActor actor,String no,AfterSaleAuditCommand command){actor.require(ActorType.MERCHANT);AfterSale sale=requireForUpdate(no);if(!actor.getId().equals(sale.getMerchantId()))throw TradeException.forbidden("merchant does not own this after-sale");if(command==null)throw TradeException.unprocessable("audit command is required");if(command.isApproved())sale.approve(trim(command.getRemark()));else sale.reject(trim(command.getRemark()));sales.save(sale);event(sale,command.isApproved()?"AFTER_SALE_APPROVED":"AFTER_SALE_REJECTED",actor,trim(command.getRemark()));if(sale.getStatus()==AfterSaleStatus.REFUND_PENDING)dispatchAfterCommit(sale);return sale;}
 @Transactional public AfterSale close(TradeActor actor,String no){actor.require(ActorType.BUYER);AfterSale sale=requireBuyerForUpdate(no,actor.getId());if(sale.getStatus()!=AfterSaleStatus.APPLYING)throw TradeException.conflict("only an applying after-sale can be closed by buyer");sale.close();sales.save(sale);event(sale,"AFTER_SALE_CLOSED_BY_BUYER",actor,"buyer_withdrew_before_audit");return sale;}
 @Transactional public AfterSale submitReturn(TradeActor actor,String no,ReturnShipmentCommand command){actor.require(ActorType.BUYER);AfterSale sale=requireBuyerForUpdate(no,actor.getId());if(command==null||blank(command.getLogisticsCompany())||blank(command.getTrackingNo()))throw TradeException.unprocessable("logisticsCompany and trackingNo are required");sale.submitReturn(command.getLogisticsCompany().trim(),command.getTrackingNo().trim());sales.save(sale);event(sale,"AFTER_SALE_RETURN_SHIPPED",actor,command.getTrackingNo().trim());return sale;}
 @Transactional public AfterSale receiveReturn(TradeActor actor,String no){actor.require(ActorType.MERCHANT);AfterSale sale=requireForUpdate(no);if(!actor.getId().equals(sale.getMerchantId()))throw TradeException.forbidden("merchant does not own this after-sale");sale.receiveReturn();sales.save(sale);if(sale.getType()==AfterSaleType.EXCHANGE){inventory.exchangeAfterSale(sale.getAfterSaleNo(),sale.getMerchantId(),saleItems.findByAfterSaleNo(sale.getAfterSaleNo()));event(sale,"AFTER_SALE_EXCHANGE_READY",actor,"pending_shipment");}else{event(sale,"AFTER_SALE_RETURN_RECEIVED",actor,"refund_pending");dispatchAfterCommit(sale);}return sale;}
 @Transactional public AfterSale shipExchange(TradeActor actor,String no,ShipmentCommand command){actor.require(ActorType.MERCHANT);AfterSale sale=requireForUpdate(no);if(!actor.getId().equals(sale.getMerchantId()))throw TradeException.forbidden("merchant does not own this after-sale");if(command==null||blank(command.getLogisticsCompany())||blank(command.getTrackingNo()))throw TradeException.unprocessable("logisticsCompany and trackingNo are required");sale.exchangeShip(command.getLogisticsCompany().trim(),command.getTrackingNo().trim());sales.save(sale);event(sale,"AFTER_SALE_EXCHANGE_SHIPPED",actor,command.getTrackingNo().trim());return sale;}
 @Transactional public AfterSale confirmExchangeReceipt(TradeActor actor,String no){actor.require(ActorType.BUYER);AfterSale sale=requireBuyerForUpdate(no,actor.getId());if(sale.getType()!=AfterSaleType.EXCHANGE)throw TradeException.conflict("only an exchange after-sale can confirm replacement receipt");sale.confirmExchangeReceipt();sales.save(sale);event(sale,"AFTER_SALE_EXCHANGE_RECEIVED",actor,"buyer_confirmed_replacement");return sale;}
 private void dispatchAfterCommit(final AfterSale sale){if(org.springframework.transaction.support.TransactionSynchronizationManager.isSynchronizationActive())org.springframework.transaction.support.TransactionSynchronizationManager.registerSynchronization(new org.springframework.transaction.support.TransactionSynchronizationAdapter(){@Override public void afterCommit(){settlement.refundAfterSale(sale);}});else settlement.refundAfterSale(sale);}
 @Transactional public AfterSale refundSucceeded(TradeActor actor,String no){actor.require(ActorType.SYSTEM);AfterSale sale=requireForUpdate(no);if(sale.getStatus()==AfterSaleStatus.REFUNDED)return sale;if(sale.getStatus()!=AfterSaleStatus.REFUND_PENDING)throw TradeException.conflict("after-sale is not awaiting refund");if(sale.getType()==AfterSaleType.RETURN_AND_REFUND)inventory.refundAfterSale(sale.getAfterSaleNo(),sale.getMerchantId(),saleItems.findByAfterSaleNo(sale.getAfterSaleNo()));sale.refund();sales.save(sale);event(sale,"AFTER_SALE_REFUNDED",actor,"simulated");return sale;}
 public List<AfterSaleView> buyerList(TradeActor actor){actor.require(ActorType.BUYER);return views(sales.findByBuyerIdOrderByIdDesc(actor.getId()));} public List<AfterSaleView> merchantList(TradeActor actor){actor.require(ActorType.MERCHANT);return views(sales.findByMerchantIdOrderByIdDesc(actor.getId()));} public AfterSaleView view(AfterSale sale){return new AfterSaleView(sale);} public AfterSaleDetail detail(TradeActor actor,String no){AfterSale sale=require(no);if(actor.getType()==ActorType.BUYER){if(!actor.getId().equals(sale.getBuyerId()))throw TradeException.forbidden("buyer does not own this after-sale");}else if(actor.getType()==ActorType.MERCHANT){if(!actor.getId().equals(sale.getMerchantId()))throw TradeException.forbidden("merchant does not own this after-sale");}else throw TradeException.forbidden("buyer or merchant actor is required");return new AfterSaleDetail(view(sale),saleItems.findByAfterSaleNo(sale.getAfterSaleNo()),timeline(events.findByAfterSaleNoOrderByIdAsc(sale.getAfterSaleNo())),evidence==null?Collections.<AfterSaleEvidence>emptyList():evidence.findByAfterSaleNoOrderByIdAsc(sale.getAfterSaleNo()));}
 private List<OrderTimelineEvent> timeline(List<OrderEvent> source){List<OrderTimelineEvent> result=new ArrayList<OrderTimelineEvent>();if(source!=null)for(OrderEvent event:source)result.add(OrderTimelineEvent.from(event));return result;}
 public Map<String,Object> buyerPage(TradeActor actor,AfterSaleStatus status,int page,int size){actor.require(ActorType.BUYER);return page(sales.pageByBuyer(actor.getId(),status,pageable(page,size)),page,size);} public Map<String,Object> merchantPage(TradeActor actor,AfterSaleStatus status,int page,int size){actor.require(ActorType.MERCHANT);return page(sales.pageByMerchant(actor.getId(),status,pageable(page,size)),page,size);} private org.springframework.data.domain.Pageable pageable(int page,int size){if(page<0||size<1||size>100||page>Integer.MAX_VALUE/size)throw TradeException.unprocessable("page must be nonnegative and size must be 1..100 without overflow");return new org.springframework.data.domain.PageRequest(page,size);} private Map<String,Object> page(org.springframework.data.domain.Page<AfterSale> result,int page,int size){Map<String,Object> data=new HashMap<String,Object>();data.put("total",result.getTotalElements());data.put("page",page);data.put("size",size);data.put("items",views(result.getContent()));return data;} private List<AfterSaleView> views(List<AfterSale> source){List<AfterSaleView> result=new ArrayList<AfterSaleView>();if(source!=null)for(AfterSale sale:source)result.add(view(sale));return result;}
 private Map<Long,Integer> appliedQuantities(String subOrderNo){Map<Long,Integer> totals=new HashMap<Long,Integer>();for(AfterSale sale:sales.findBySubOrderNoOrderByIdAsc(subOrderNo)){if(sale.getStatus()==AfterSaleStatus.REJECTED||sale.getStatus()==AfterSaleStatus.CLOSED)continue;for(AfterSaleItem item:saleItems.findByAfterSaleNo(sale.getAfterSaleNo())){Integer quantity=totals.get(item.getOrderItemId());totals.put(item.getOrderItemId(),(quantity==null?0:quantity)+item.getQuantity());}}return totals;} private List<String> verifiedEvidence(TradeActor actor,List<String> names){if(names==null||names.isEmpty())return Collections.emptyList();if(names.size()>10)throw TradeException.unprocessable("at most 10 after-sale evidence files are allowed");Set<String> unique=new HashSet<String>();List<String> verified=new ArrayList<String>();for(String raw:names){String name=raw==null?null:raw.trim();if(blank(name)||!unique.add(name))throw TradeException.unprocessable("after-sale evidence file names must be unique and nonblank");verified.add(name);}for(String name:verified)files.requirePermanentBuyerFile(actor.getId(),name);return verified;} private void event(AfterSale sale,String type,TradeActor actor,String payload){events.save(new OrderEvent(sale.getOrderNo(),sale.getSubOrderNo(),sale.getAfterSaleNo(),type,actor.getId(),actor.getType().name(),payload==null?"":payload));} private AfterSale require(String no){AfterSale sale=sales.findByAfterSaleNo(no);if(sale==null)throw TradeException.notFound("after-sale was not found");return sale;} private AfterSale requireForUpdate(String no){AfterSale sale=sales.findByAfterSaleNoForUpdate(no);if(sale==null)throw TradeException.notFound("after-sale was not found");return sale;} private AfterSale requireBuyer(String no,Long buyerId){AfterSale sale=require(no);if(!buyerId.equals(sale.getBuyerId()))throw TradeException.forbidden("buyer does not own this after-sale");return sale;} private AfterSale requireBuyerForUpdate(String no,Long buyerId){AfterSale sale=requireForUpdate(no);if(!buyerId.equals(sale.getBuyerId()))throw TradeException.forbidden("buyer does not own this after-sale");return sale;} private TradeSubOrder requireSub(String no){TradeSubOrder sub=subOrders.findBySubOrderNo(no);if(sub==null)throw TradeException.notFound("sub order was not found");return sub;} private TradeSubOrder requireSubForUpdate(String no){TradeSubOrder sub=subOrders.findBySubOrderNoForUpdate(no);if(sub==null)throw TradeException.notFound("sub order was not found");return sub;} private TradeOrder requireOrder(String no){TradeOrder order=orders.findByOrderNo(no);if(order==null)throw TradeException.notFound("order was not found");return order;} private boolean blank(String v){return v==null||v.trim().isEmpty();} private String trim(String v){return v==null?null:v.trim();}
}
