package com.own.order.controller;
import com.own.face.trade.TradeActor; import com.own.face.trade.TradeHeaders; import com.own.face.util.Resp; import com.own.face.util.base.BaseController; import com.own.order.dto.*; import com.own.order.service.AfterSaleService; import jakarta.servlet.http.HttpServletRequest; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/after-sales") public class AfterSaleController extends BaseController {
 private final AfterSaleService service; public AfterSaleController(AfterSaleService service){this.service=service;}
 @PostMapping public Resp create(@RequestBody CreateAfterSaleCommand command,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.create(actor,command)),201,"created");}
 @GetMapping public Resp mine(HttpServletRequest request){return new Resp(service.buyerList(TradeHeaders.actor(request)));}
 @GetMapping("/merchant") public Resp merchant(HttpServletRequest request){return new Resp(service.merchantList(TradeHeaders.actor(request)));}
 @GetMapping("/page") public Resp minePage(@RequestParam(required=false) com.own.order.domain.AfterSaleStatus status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size,HttpServletRequest request){return new Resp(service.buyerPage(TradeHeaders.actor(request),status,page,size));}
 @GetMapping("/merchant/page") public Resp merchantPage(@RequestParam(required=false) com.own.order.domain.AfterSaleStatus status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size,HttpServletRequest request){return new Resp(service.merchantPage(TradeHeaders.actor(request),status,page,size));}
 @GetMapping("/{afterSaleNo}") public Resp detail(@PathVariable String afterSaleNo,HttpServletRequest request){return new Resp(service.detail(TradeHeaders.actor(request),afterSaleNo));}
 @PostMapping("/{afterSaleNo}/close") public Resp close(@PathVariable String afterSaleNo,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.close(actor,afterSaleNo)));}
 @PostMapping("/{afterSaleNo}/audit") public Resp audit(@PathVariable String afterSaleNo,@RequestBody AfterSaleAuditCommand command,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.audit(actor,afterSaleNo,command)));}
 @PostMapping("/{afterSaleNo}/return-shipment") public Resp submitReturn(@PathVariable String afterSaleNo,@RequestBody ReturnShipmentCommand command,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.submitReturn(actor,afterSaleNo,command)));}
 @PostMapping("/{afterSaleNo}/receive-return") public Resp receiveReturn(@PathVariable String afterSaleNo,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.receiveReturn(actor,afterSaleNo)));}
 @PostMapping("/{afterSaleNo}/exchange-shipment") public Resp exchangeShipment(@PathVariable String afterSaleNo,@RequestBody ShipmentCommand command,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.shipExchange(actor,afterSaleNo,command)));}
 @PostMapping("/{afterSaleNo}/exchange-receive") public Resp receiveExchange(@PathVariable String afterSaleNo,HttpServletRequest request){TradeActor actor=TradeHeaders.actor(request);TradeHeaders.idempotencyKey(request);return new Resp(service.view(service.confirmExchangeReceipt(actor,afterSaleNo)));}
}
