package com.own.product.controller;
import com.own.face.util.Resp; import com.own.product.dao.ProductDao; import com.own.product.domain.Product; import java.util.*; import org.junit.jupiter.api.Test; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
public class MerchantProductControllerTest {
 @Test public void browseUsesStableAscendingProductIdPaginationWithoutInternalStock(){ProductDao dao=mock(ProductDao.class);Product two=product(2L,"Tea"),one=product(1L,"Tea"),off=product(3L,"Tea");two.setStocksNum("99");off.setSaleStatus("OFF_SHELF");when(dao.queryProduct()).thenReturn(Arrays.asList(two,off,one));MerchantProductController controller=new MerchantProductController(dao);Resp response=controller.browse(null,null,"tea",0,20);Map data=(Map)response.getData();List<com.own.product.dto.PublicProductView> products=(List<com.own.product.dto.PublicProductView>)data.get("items");assertEquals(2,products.size());assertEquals(Long.valueOf(1L),products.get(0).getId());assertEquals(Long.valueOf(2L),products.get(1).getId());assertFalse(Arrays.asList(products.get(1).getClass().getDeclaredFields()).toString().contains("stocksNum"));}

 @Test public void publicDetailReturnsAvailableProductOnly(){ProductDao dao=mock(ProductDao.class);Product available=product(1L,"Tea");available.setStocksNum("99");when(dao.queryProductById(1L)).thenReturn(available);MerchantProductController controller=new MerchantProductController(dao);com.own.product.dto.PublicProductView view=(com.own.product.dto.PublicProductView)controller.detail(1L).getData();assertEquals(Long.valueOf(1L),view.getId());assertFalse(Arrays.asList(view.getClass().getDeclaredFields()).toString().contains("stocksNum"));}
 @Test public void merchantCatalogIncludesOnlyOwnOffShelfProducts(){ProductDao dao=mock(ProductDao.class);Product mine=product(1L,"Tea"),other=product(2L,"Coffee");mine.setPartyId(7L);mine.setSaleStatus("OFF_SHELF");other.setPartyId(8L);when(dao.queryProduct()).thenReturn(Arrays.asList(other,mine));MerchantProductController controller=new MerchantProductController(dao);org.springframework.mock.web.MockHttpServletRequest request=new org.springframework.mock.web.MockHttpServletRequest();request.addHeader("X-Actor-Id","7");request.addHeader("X-Actor-Type","MERCHANT");Resp response=controller.mine(null,null,"OFF_SHELF",0,20,request);List<Product> products=(List<Product>)((Map)response.getData()).get("items");assertEquals(1,products.size());assertEquals(Long.valueOf(1L),products.get(0).getId());}
 @Test public void merchantPriceUpdateWritesOwnAuditEntry(){ProductDao dao=mock(ProductDao.class);com.own.product.audit.repository.ProductPriceAuditRepository audits=mock(com.own.product.audit.repository.ProductPriceAuditRepository.class);Product item=product(3L,"Tea");item.setPartyId(7L);item.setOriginalPrice("10.00");when(dao.queryProductById(3L)).thenReturn(item);when(dao.save(item)).thenReturn(item);MerchantProductController controller=new MerchantProductController(dao,audits);com.own.product.dto.MerchantProductCommand command=new com.own.product.dto.MerchantProductCommand();command.setName("Tea");command.setSkuCode("TEA-1");command.setOriginalPrice("12.00");command.setPriceChangeReason("seasonal update");org.springframework.mock.web.MockHttpServletRequest request=new org.springframework.mock.web.MockHttpServletRequest();request.addHeader("X-Actor-Id","7");request.addHeader("X-Actor-Type","MERCHANT");request.addHeader("Idempotency-Key","test-product-audit");controller.update(3L,command,request);verify(audits).save(org.mockito.ArgumentMatchers.any(com.own.product.audit.domain.ProductPriceAudit.class));}
 private Product product(Long id,String name){Product product=new Product();product.setId(id);product.setName(name);product.setSaleStatus("AVAILABLE");return product;}

 @Test public void merchantCannotSetPromotionPriceAboveOriginalPrice(){ProductDao dao=mock(ProductDao.class);MerchantProductController controller=new MerchantProductController(dao);com.own.product.dto.MerchantProductCommand command=new com.own.product.dto.MerchantProductCommand();command.setPartyId(1L);command.setName("Tea");command.setSkuCode("TEA-1");command.setOriginalPrice("10.00");command.setPromotionPrice("10.01");org.springframework.mock.web.MockHttpServletRequest request=new org.springframework.mock.web.MockHttpServletRequest();request.addHeader("X-Actor-Id","1");request.addHeader("X-Actor-Type","MERCHANT");request.addHeader("Idempotency-Key","test-product-price");assertThrows(com.own.face.trade.TradeException.class,()->controller.create(command,request));}

 @Test public void missingLegacyProductUsesNotFoundInsteadOfNullPointer(){ProductDao dao=mock(ProductDao.class);ProductController controller=new ProductController();try{java.lang.reflect.Field field=ProductController.class.getDeclaredField("productDao");field.setAccessible(true);field.set(controller,dao);}catch(Exception exception){throw new AssertionError(exception);}assertThrows(com.own.face.trade.TradeException.class,()->controller.getProduct(999L));}

 @Test public void browseRejectsPageMultiplicationOverflow(){ProductDao dao=mock(ProductDao.class);MerchantProductController controller=new MerchantProductController(dao);assertThrows(com.own.face.trade.TradeException.class,()->controller.browse(null,null,null,Integer.MAX_VALUE,2));}

 @Test public void legacyQueryRejectsCypherSyntaxInIdentifiers(){ProductDao dao=mock(ProductDao.class);ProductController controller=new ProductController();try{java.lang.reflect.Field field=ProductController.class.getDeclaredField("productDao");field.setAccessible(true);field.set(controller,dao);}catch(Exception exception){throw new AssertionError(exception);}Map<String,Object> values=new HashMap<String,Object>();values.put("partyId","1}) MATCH (n) DETACH DELETE n //");assertThrows(com.own.face.trade.TradeException.class,()->controller.queryProduct(values));}
}
