#sms url
ems.serviceURL=${SMS_SERVICE_URL:}
ems.sn=${SMS_SN:}
ems.pwd=${SMS_PASSWORD:}

#send Email config
ems.host=${MAIL_HOST:}
ems.auth=${MAIL_AUTH:false}
ems.from=${MAIL_FROM:}

#mail.subject = subject
ems.subject=\u90AE\u7BB1\u9A8C\u8BC1
ems.title=\u6C47\u91D1\u8D37-\u8BF7\u6FC0\u6D3B\u60A8\u7684\u90AE\u7BB1\uFF0C\u5B8C\u6210\u8BA4\u8BC1

ems.user=${MAIL_USER:}
ems.password=${MAIL_PASSWORD:}

#send Jpush
ems.appKey=${JPUSH_APP_KEY:}
ems.masterSecret=${JPUSH_MASTER_SECRET:}
