name: java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
     - name: pull latest code
       uses: actions/checkout@v3
       
     - name: Set up JDK 1.8
       uses: actions/setup-java@v3 # 安装java环境的action
       with:
         java-version: '8.0' # 指定jkd版本
         distribution: 'temurin'
         cache: maven # 使用maven缓存，避免每次构建项目时都要重新下载maven依赖

