FROM java:8-jre
MAINTAINER Blucezhang <Blucezhang@outlook.com>

ADD ../../target/own-eureka-server-1.0-ALPHA.jar /app/
CMD ["java","-Xmx200m","-jar","/app/rown-eureka-server-1.0-ALPHA.jar"]

EXPOSE 8002